DROP DATABASE IF EXISTS  TimeLine;
CREATE DATABASE TimeLine;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Event;
CREATE TABLE Users
(
	ID INT PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Age INT NOT NULL,
	Gender VARCHAR(6)
)
CREATE TABLE Event
(
	Action VARCHAR NOT NULL,
	Duration INT NOT NULL
)
